services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/mnt/markdown_to_html_converter
    environment:
      - PYTHONPATH=/mnt/markdown_to_html_converter
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
